#pragma config(Sensor, S1,     TouchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     GyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorA,          moteurA,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//exercice1
/*
setMotorSpeed(moteurA,-20);
delay(4000);
setMotorSpeed(moteurA,0);
delay(500);
*/

//exercice2
/*
setMotorSpeed(moteurA,50);
while(getTouchValue(S1)==0){}
setMotorSpeed(moteurA,0);
delay(500);
*/

//exercice3
/*
	int sens = 1;
	long t1,t2;
	t1=nSysTime-1000;
	t2=nSysTime-500;
	while(t2-t1>300){
		while(getTouchValue(S1)==0){}
		t1=t2;
		t2=nSysTime;
		sens=-sens;
		setMotorSpeed(moteurA,sens*20);
		while(getTouchValue(S1)==1){}
	}
	setMotorSpeed(moteurA,0);
  delay(500);
*/


//exercice4
/*
	int puissance = 10;
	int sens = 0;
	while(getButtonPress(buttonEnter)==0){
		if (getButtonPress(buttonRight)==1){
				sens = 1;
				setMotorSpeed(moteurA,sens*puissance);
		}
		else if (getButtonPress(buttonLeft)==1){
				sens = -1;
				setMotorSpeed(moteurA,sens*puissance);
		}
		else if (getButtonPress(buttonUp)==1){
				if (puissance>100) {}
				else {
				puissance=puissance+10;
				delay(200);
				setMotorSpeed(moteurA,sens*puissance);
			}
		}
			else if (getButtonPress(buttonDown)==1){
					if (puissance>0) {
				puissance=puissance-10;
				delay(200);
				setMotorSpeed(moteurA,sens*puissance);
			}
		}
	}
		setMotorSpeed(moteurA,0);
  	delay(500);
*/







}
